id: AAE6D95D6
title: Short Guru Yoga of the Noble Lord, All-Knowing Tsongkhapa
type: translation
pechas:
- IB52B7A6D
- IA86B8823
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:13:12.260926
  last_modified_at: 2023-01-04 12:13:12.260932
  collections:
  - Jamyang Khyentse Chökyi Lodrö Series
  - Works of Tibetan Masters
alignment_to_base:
  IB52B7A6D/2610: 275A
  IA86B8823/6AD7: 275A
